version: '3.8'

services:
    # Application Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel
        ports:
            - "9000:9000"
        depends_on:
            - db

    # Database Service
    db:
        image: mysql:8.0
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: procurement
            MYSQL_ROOT_PASSWORD: password  # Set the root password only
            # Remove MYSQL_USER and MYSQL_PASSWORD
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
        ports:
            - "3307:3306"

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
        driver: local
